// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkNDPCTD1ND0YA1qVctsBS56w7yWvD8oY',
    appId: '1:544995961689:web:b1e682e3e22f7c3f7fba48',
    messagingSenderId: '544995961689',
    projectId: 'connectfriends-4f495',
    authDomain: 'connectfriends-4f495.firebaseapp.com',
    storageBucket: 'connectfriends-4f495.appspot.com',
    measurementId: 'G-SXW3EB2PHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq_-4sCZtX3lG_6_yByFMGPPqBI-BMIG8',
    appId: '1:544995961689:android:cfa2b004528a18c37fba48',
    messagingSenderId: '544995961689',
    projectId: 'connectfriends-4f495',
    storageBucket: 'connectfriends-4f495.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFA0S-6JgEvfPTnQtI3vQGHFH3_07jB14',
    appId: '1:544995961689:ios:1d122cbb103b4c1b7fba48',
    messagingSenderId: '544995961689',
    projectId: 'connectfriends-4f495',
    storageBucket: 'connectfriends-4f495.appspot.com',
    iosBundleId: 'com.example.connectFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFA0S-6JgEvfPTnQtI3vQGHFH3_07jB14',
    appId: '1:544995961689:ios:c11c58615c3bb8357fba48',
    messagingSenderId: '544995961689',
    projectId: 'connectfriends-4f495',
    storageBucket: 'connectfriends-4f495.appspot.com',
    iosBundleId: 'com.example.connectFriends.RunnerTests',
  );
}
